openapi: 3.1.0
info:
  title: Arduino Project Manager API
  description: API for managing Arduino projects using arduino-cli, with cached file listing and just-in-time file reading.
  version: 2.0.0
servers:
  - url: https://3927-70-119-126-223.ngrok-free.app
    description: Ngrok tunnel URL for the FastAPI server

paths:
  /check_folder:
    post:
      operationId: checkFolder
      summary: Check if project folder exists
      description: Check if the specified project folder exists in ../Arduino/. Use this to verify existence before creating, reading, updating, compiling, or uploading a project.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                  description: The name of the Arduino project. Must be a valid folder name without special characters.
                  minLength: 1
                  maxLength: 50
              required:
                - project_name
      responses:
        "200":
          description: Folder existence status
          content:
            application/json:
              schema:
                type: object
                properties:
                  exists:
                    type: boolean
        "500":
          description: Server error

  /read_files:
    post:
      deprecated: true
      operationId: readFiles
      summary: DEPRECATED - Return only filenames in project
      description: >
        Deprecated. Previously returned content of all files, but now only returns a list of filenames to prevent huge payloads.  
        For file content, call /read_file with a specific path.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                  description: The Arduino project name
                  minLength: 1
                  maxLength: 50
              required:
                - project_name
      responses:
        "200":
          description: List of filenames
          content:
            application/json:
              schema:
                type: object
                properties:
                  files:
                    type: array
                    items:
                      type: string
                  message:
                    type: string
        "404":
          description: Project folder not found
        "500":
          description: Server error

  /list_files_in_project:
    get:
      operationId: listFilesInProject
      summary: List all filenames (no content) in a project
      description: Returns a list of all file paths for the specified project, from the in-memory cache. If not cached, tries to refresh. No contents returned.
      parameters:
        - in: query
          name: project_name
          schema:
            type: string
          required: true
          description: The Arduino project name
      responses:
        "200":
          description: Filenames
          content:
            application/json:
              schema:
                type: object
                properties:
                  project_name:
                    type: string
                  files:
                    type: array
                    items:
                      type: string
        "404":
          description: Project folder not found
        "500":
          description: Server error

  /read_file:
    post:
      operationId: readFile
      summary: Read contents of a single file
      description: Returns the content of the specified file, on demand.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                  description: The Arduino project name
                file_path:
                  type: string
                  description: The relative path of the file in the project folder (e.g., "src/main.cpp").
              required:
                - project_name
                - file_path
      responses:
        "200":
          description: File contents
          content:
            application/json:
              schema:
                type: object
                properties:
                  file_path:
                    type: string
                  content:
                    type: string
        "404":
          description: Project folder or file not found
        "500":
          description: Server error

  /create_project:
    post:
      operationId: createProject
      summary: Create a new project folder and an optional file
      description: >
        Creates a new project folder. By default, also creates <project_name>.ino in the root, or the specified file_path if provided.  
        Returns 400 if the folder already exists.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                sketch_content:
                  type: string
                file_path:
                  type: string
              required:
                - project_name
                - sketch_content
      responses:
        "200":
          description: Project creation status
        "400":
          description: Project folder already exists
        "500":
          description: Server error

  /update_sketch:
    post:
      operationId: updateSketch
      summary: Update or create a file in an existing project
      description: >
        Updates (or creates) a file. If file_path is omitted, updates <project_name>.ino in the project root.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                sketch_content:
                  type: string
                file_path:
                  type: string
              required:
                - project_name
                - sketch_content
      responses:
        "200":
          description: File update status
        "404":
          description: Project folder not found
        "500":
          description: Server error

  /compile_project:
    post:
      operationId: compileProject
      summary: Compile project using arduino-cli
      description: >
        Compile the specified project, assuming <project_name>.ino is in the root.  
        If your .ino is located differently, rename or adapt the code.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
              required:
                - project_name
      responses:
        "200":
          description: Compilation result
        "404":
          description: Project or .ino not found
        "500":
          description: Server error

  /upload_project:
    post:
      operationId: uploadProject
      summary: Upload compiled project to Arduino
      description: >
        Upload to the specified port, expecting <project_name>.ino in the root.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                port:
                  type: string
              required:
                - project_name
                - port
      responses:
        "200":
          description: Upload result
        "404":
          description: Project or .ino not found
        "500":
          description: Server error

  /list_projects:
    get:
      operationId: listProjects
      summary: List all project folders
      description: >
        Lists all project folders in the Arduino/ directory (cached), excluding hidden or system directories.
      responses:
        "200":
          description: List of project folders
        "500":
          description: Server error

