openapi: 3.1.0
info:
  title: Arduino Project Manager API
  description: API for managing Arduino projects using arduino-cli, with caching for project and library files, just-in-time reading, and read-only library browsing.
  version: 2.1.0
servers:
  - url: https://3927-70-119-126-223.ngrok-free.app
    description: Ngrok tunnel URL for the FastAPI server

paths:
  /check_folder:
    post:
      operationId: checkFolder
      summary: Check if project folder exists
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
              required:
                - project_name
      responses:
        "200":
          description: Existence status
        "500":
          description: Server error

  /read_files:
    post:
      deprecated: true
      operationId: readFiles
      summary: DEPRECATED - Only returns filenames
      description: >
        Deprecated. Formerly returned all file contents, now only returns filenames to avoid huge payloads.  
        Use /read_file to fetch contents of an individual file.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
              required:
                - project_name
      responses:
        "200":
          description: Filenames
        "404":
          description: Project not found
        "500":
          description: Server error

  /list_files_in_project:
    get:
      operationId: listFilesInProject
      summary: List filenames in a project
      parameters:
        - in: query
          name: project_name
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Filenames
        "404":
          description: Project not found
        "500":
          description: Server error

  /read_file:
    post:
      operationId: readFile
      summary: Read contents of a single project file
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                file_path:
                  type: string
              required:
                - project_name
                - file_path
      responses:
        "200":
          description: File contents
        "404":
          description: File or project not found
        "500":
          description: Server error

  /create_project:
    post:
      operationId: createProject
      summary: Create a new project folder and one file
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                sketch_content:
                  type: string
                file_path:
                  type: string
              required:
                - project_name
                - sketch_content
      responses:
        "200":
          description: Project creation
        "400":
          description: Project exists
        "500":
          description: Server error

  /update_sketch:
    post:
      operationId: updateSketch
      summary: Update or create a file in an existing project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                sketch_content:
                  type: string
                file_path:
                  type: string
              required:
                - project_name
                - sketch_content
      responses:
        "200":
          description: Update success
        "404":
          description: Project not found
        "500":
          description: Server error

  /compile_project:
    post:
      operationId: compileProject
      summary: Compile a project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
              required:
                - project_name
      responses:
        "200":
          description: Compilation result
        "404":
          description: Project or main .ino not found
        "500":
          description: Error compiling

  /upload_project:
    post:
      operationId: uploadProject
      summary: Upload project to an Arduino board
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                port:
                  type: string
              required:
                - project_name
                - port
      responses:
        "200":
          description: Upload result
        "404":
          description: Project or main .ino not found
        "500":
          description: Error uploading

  /list_projects:
    get:
      operationId: listProjects
      summary: List all project folders
      responses:
        "200":
          description: List of project folders
        "500":
          description: Server error

  /list_libraries:
    get:
      operationId: listLibraries
      summary: List library folders in Arduino/libraries
      responses:
        "200":
          description: Library list
        "500":
          description: Server error

  /list_files_in_library:
    get:
      operationId: listFilesInLibrary
      summary: List filenames in a specific library
      parameters:
        - in: query
          name: library_name
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Filenames
        "404":
          description: Library not found
        "500":
          description: Server error

  /read_library_file:
    post:
      operationId: readLibraryFile
      summary: Read a single file from a library (read-only)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                library_name:
                  type: string
                file_path:
                  type: string
              required:
                - library_name
                - file_path
      responses:
        "200":
          description: File contents
        "404":
          description: File/library not found
        "500":
          description: Server error

  /copy_library_example:
    post:
      operationId: copyLibraryExample
      summary: Copy an example folder from a library into a local project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                library_name:
                  type: string
                example_folder:
                  type: string
                new_project_name:
                  type: string
              required:
                - library_name
                - example_folder
                - new_project_name
      responses:
        "200":
          description: Copy success
        "404":
          description: Library or example not found
        "500":
          description: Server error

  # -----------------------------
  # Library Management Endpoints
  # -----------------------------
  /list_libraries_installed:
    get:
      operationId: listLibrariesInstalled
      summary: Run `arduino-cli lib list` to see installed libraries
      responses:
        "200":
          description: CLI output
        "500":
          description: Error listing libraries

  /search_library:
    post:
      operationId: searchLibrary
      summary: Search libraries by keyword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
              required:
                - keyword
      responses:
        "200":
          description: CLI output
        "500":
          description: Error searching libraries

  /install_library:
    post:
      operationId: installLibrary
      summary: Install a library
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                library_name:
                  type: string
              required:
                - library_name
      responses:
        "200":
          description: CLI output
        "500":
          description: Error installing library

  /uninstall_library:
    post:
      operationId: uninstallLibrary
      summary: Uninstall a library
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                library_name:
                  type: string
              required:
                - library_name
      responses:
        "200":
          description: CLI output
        "500":
          description: Error uninstalling library

  /update_library:
    post:
      operationId: updateLibrary
      summary: Update a specific library
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                library_name:
                  type: string
              required:
                - library_name
      responses:
        "200":
          description: CLI output
        "500":
          description: Error updating library

  /update_all_libraries:
    post:
      operationId: updateAllLibraries
      summary: Update all libraries
      responses:
        "200":
          description: CLI output
        "500":
          description: Error updating libraries

  # -----------------------------
  # Board/Core Management
  # -----------------------------
  /list_connected_boards:
    get:
      operationId: listConnectedBoards
      summary: List boards currently connected
      responses:
        "200":
          description: CLI output
        "500":
          description: Error listing boards

  /search_cores:
    post:
      operationId: searchCores
      summary: Search board cores
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                keyword:
                  type: string
              required:
                - keyword
      responses:
        "200":
          description: CLI output
        "500":
          description: Error searching cores

  /install_core:
    post:
      operationId: installCore
      summary: Install a board core
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                core:
                  type: string
              required:
                - core
      responses:
        "200":
          description: CLI output
        "500":
          description: Error installing core

  /uninstall_core:
    post:
      operationId: uninstallCore
      summary: Uninstall a board core
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                core:
                  type: string
              required:
                - core
      responses:
        "200":
          description: CLI output
        "500":
          description: Error uninstalling core

